---
title: "Work Experience"
---

### At Iowa State University

-   Research Assistant
    - Working on a project in collaboration with the [Dept. of the Earth, Atmosphere, and Climate](https://earth-atmosphere-climate.iastate.edu/) at [Iowa State University](https://earth-atmosphere-climate.iastate.edu/), *Spring 2023 - Present*.
    
-   Lab Instructor
    -   **STAT 342** : Introduction to the Theory of Probability and Statistics II, *Spring 2023*.   
    -   **STAT 342** : Introduction to the Theory of Probability and Statistics II, *Fall 2022*.
    -   **STAT 326**: Introduction to Business Statistics II, *Fall 2021*.    
    -   **STAT 101** : Introduction to Statistics, *Fall 2021*.

-   Grader
    -   **STAT 542** : Theory of Probability and Statistics I, *Fall 2022*.
    -   **STAT 642** : Advanced Probability Theory, *Spring 2022*.    
    -   **STAT 322** : Probabilistic Methods for Electrical Engineers, *Spring 2022*.
    -   **STAT 587** : Statistical Methods for Research Workers, *Summer 2021*.   
    -   **STAT 231**: Probability and Statistical Inference for Engineers, *Spring 2021*,

### At Wells Fargo

-   Quantitative Analyst Intern
    - **Summer 2024** : Commercial Loss Forecasting team, Risk Modeling Group CoE
    - **Summer 2023** : Balance Sheet and Stress Test Validation team, Corporate Model Risk CoE

    
